 COMPUTATIONAL STATISTICS OF THE INDEX 1 TWO BIT ADDING PROBLEM USING  MEBDFI

 NUMBER OF EQUATIONS : 350
  
 RESULT WITH THE FOLLOWING TOL :
 RTOL = 0.100000000000000019E-01 
 ATOL = 0.100000000000000019E-01 


 KFLAG = -3 FROM INTEGRATOR AT T =    .27791119E+01
  CORRECTOR CONVERGENCE COULD NOT BE ACHIEVED



IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL
 
 NUMERICAL SOLUTION
 
                                               SCD
     SOLUTION COMPONENT                  -------------    IGNORE
                                         ABS        REL 
 
USED COMPONENTS FOR SCD                     3          3
SCD OF Y (MAXIMUM NORM)                  3.51       2.82
SCD OF Y (EUCLIDIAN NORM)                3.50       6.49
USING RELATIVE ERROR YIELDS SCD :                   2.82
 
 LAST STEP SIZE                         .269584D+00
 LAST ORDER OF THE METHOD                      3
 MAXIMUM ORDER USED SO FAR                     4
 TOTAL NUMBER OF STEPS TAKEN                1770
 TOTAL NUMBER OF FAILED STEPS                279
 NUMBER OF RESIDUAL EVALUATIONS           211704
 NUMBER OF JACOBIAN EVALUATIONS              581
 NUMBER OF FACTORIZATION                     581
 NUMBER OF BACKSOLVES                       7772
 NUMBER OF CORRECT DIGITS                   2.82
 CPU TIME                                479.680
 ---------------------------------------------
 RESULT WITH THE FOLLOWING TOL :
 RTOL = 0.100000000000000024E-02 
 ATOL = 0.100000000000000024E-02 


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL
 
 NUMERICAL SOLUTION
 
                                               SCD
     SOLUTION COMPONENT                  -------------    IGNORE
                                         ABS        REL 
 
USED COMPONENTS FOR SCD                     3          3
SCD OF Y (MAXIMUM NORM)                  3.51       3.37
SCD OF Y (EUCLIDIAN NORM)                3.57       7.75
USING RELATIVE ERROR YIELDS SCD :                   3.37
 
 LAST STEP SIZE                         .171398D+00
 LAST ORDER OF THE METHOD                      3
 MAXIMUM ORDER USED SO FAR                     5
 TOTAL NUMBER OF STEPS TAKEN                2813
 TOTAL NUMBER OF FAILED STEPS                262
 NUMBER OF RESIDUAL EVALUATIONS           234321
 NUMBER OF JACOBIAN EVALUATIONS              634
 NUMBER OF FACTORIZATION                     634
 NUMBER OF BACKSOLVES                      11786
 NUMBER OF CORRECT DIGITS                   3.37
 CPU TIME                                570.040
 ---------------------------------------------
 RESULT WITH THE FOLLOWING TOL :
 RTOL = 0.100000000000000032E-03 
 ATOL = 0.100000000000000032E-03 


IERR IS NON-ZERO BECAUSE OF AN ILLEGAL FUNCTION   CALL
 
 NUMERICAL SOLUTION
 
                                               SCD
     SOLUTION COMPONENT                  -------------    IGNORE
                                         ABS        REL 
 
USED COMPONENTS FOR SCD                     3          3
SCD OF Y (MAXIMUM NORM)                  3.51       3.40
SCD OF Y (EUCLIDIAN NORM)                4.05       7.82
USING RELATIVE ERROR YIELDS SCD :                   3.40
 
 LAST STEP SIZE                         .203593D-01
 LAST ORDER OF THE METHOD                      3
 MAXIMUM ORDER USED SO FAR                     5
 TOTAL NUMBER OF STEPS TAKEN                4824
 TOTAL NUMBER OF FAILED STEPS                395
 NUMBER OF RESIDUAL EVALUATIONS           350299
 NUMBER OF JACOBIAN EVALUATIONS              944
 NUMBER OF FACTORIZATION                     944
 NUMBER OF BACKSOLVES                      18954
 NUMBER OF CORRECT DIGITS                   3.40
 CPU TIME                                869.180
 ---------------------------------------------
 RESULT WITH THE FOLLOWING TOL :
 RTOL = 0.100000000000000042E-04 
 ATOL = 0.100000000000000042E-04 


 KFLAG = -2 FROM INTEGRATOR AT T =    .14499524E+03  H =   .17997972E-05
  THE REQUESTED ERROR IS SMALLER THAN CAN BE HANDLED


 MEBDFI RETURN INDEX =          -2 
